// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOatoDEfm_9Akr3A5OlrB4q_I7iOTkpEg',
    appId: '1:1096542309644:web:e40834fe3a1e77401ccd29',
    messagingSenderId: '1096542309644',
    projectId: 'med-tracker-bbf10',
    authDomain: 'med-tracker-bbf10.firebaseapp.com',
    storageBucket: 'med-tracker-bbf10.firebasestorage.app',
    measurementId: 'G-274LJN1NKN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtKRRCrlrvzg0jfFDjULeSmNO5t_cQ8tY',
    appId: '1:1096542309644:android:9e93abe666990fcb1ccd29',
    messagingSenderId: '1096542309644',
    projectId: 'med-tracker-bbf10',
    storageBucket: 'med-tracker-bbf10.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNkyP9xihAtuYFT8uhHpYFGwBI_iPrbOM',
    appId: '1:1096542309644:ios:16ddd0c4dbfe2a691ccd29',
    messagingSenderId: '1096542309644',
    projectId: 'med-tracker-bbf10',
    storageBucket: 'med-tracker-bbf10.firebasestorage.app',
    iosBundleId: 'com.medicinetracker.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNkyP9xihAtuYFT8uhHpYFGwBI_iPrbOM',
    appId: '1:1096542309644:ios:f0637e50cfa3f31e1ccd29',
    messagingSenderId: '1096542309644',
    projectId: 'med-tracker-bbf10',
    storageBucket: 'med-tracker-bbf10.firebasestorage.app',
    iosBundleId: 'com.example.projectoDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOatoDEfm_9Akr3A5OlrB4q_I7iOTkpEg',
    appId: '1:1096542309644:web:f660ee7d9aa18f491ccd29',
    messagingSenderId: '1096542309644',
    projectId: 'med-tracker-bbf10',
    authDomain: 'med-tracker-bbf10.firebaseapp.com',
    storageBucket: 'med-tracker-bbf10.firebasestorage.app',
    measurementId: 'G-DMV8T3D9RZ',
  );

}